### ISSUE TITLE
Last update brokes everything

### ISSUE THREAD

**Issue by kKen94** [3DGenomes/ngx-resizable#3]
With the v1.8.0 update there isn't any module to import

**Comment by mikegoodstadt** [comment]
Apologies - I will check what I did wrong right now...

**Comment by kKen94** [comment]
Thank you ☺ This library is fantastic!

**Comment by mikegoodstadt** [comment]
Yup - published from the projects dir (pre gzip method...) rather than publishing the gzip directly. Changed README to clarify it for the next time (for me ;P). Hope it is all good now - see these StackBlitzes:
https://stackblitz.com/edit/3dgenomes-ngx-resizable-181/
https://stackblitz.com/edit/3dgenomes-ngx-resizable-vert-181/
